import { Student, ClassInfo, Teacher, StudentQuizSubmission, CalendarEvent } from './types';

// ─── Classes ──────────────────────────────────────────────────────────────────
// School covers Class 6–9, sections A and B each.
// This teacher (Sanjana Shah) is class teacher of 6A and teaches
// History & Social Studies to 6A, 7A, 8A, and 9A.

export const mockClasses: ClassInfo[] = [
  { id: '6A', name: 'Class 6', section: 'A', studentsCount: 30, performance: 84, isClassTeacher: true  },
  { id: '6B', name: 'Class 6', section: 'B', studentsCount: 30, performance: 79, isClassTeacher: false },
  { id: '7A', name: 'Class 7', section: 'A', studentsCount: 30, performance: 81, isClassTeacher: false },
  { id: '7B', name: 'Class 7', section: 'B', studentsCount: 30, performance: 76, isClassTeacher: false },
  { id: '8A', name: 'Class 8', section: 'A', studentsCount: 30, performance: 87, isClassTeacher: false },
  { id: '8B', name: 'Class 8', section: 'B', studentsCount: 30, performance: 83, isClassTeacher: false },
  { id: '9A', name: 'Class 9', section: 'A', studentsCount: 30, performance: 91, isClassTeacher: false },
  { id: '9B', name: 'Class 9', section: 'B', studentsCount: 30, performance: 88, isClassTeacher: false },
];

// ─── Teacher ──────────────────────────────────────────────────────────────────
export const mockTeacher: Teacher = {
  name: 'Ms. Sanjana Shah',
  role: 'Senior Academic Lead',
  avatar: 'https://picsum.photos/seed/Sanjana/200/200',
  classTeacherOf: '6A',
  subjects: [
    {
      id: 'sub1',
      name: 'History',
      assignedClasses: [
        { classId: '6A', section: 'A' },
        { classId: '7A', section: 'A' },
        { classId: '8A', section: 'A' },
        { classId: '9A', section: 'A' },
      ],
    },
    {
      id: 'sub2',
      name: 'Geography',
      assignedClasses: [
        { classId: '6A', section: 'A' },
        { classId: '7A', section: 'A' },
      ],
    },
    {
      id: 'sub3',
      name: 'Civics',
      assignedClasses: [
        { classId: '8A', section: 'A' },
        { classId: '9A', section: 'A' },
      ],
    },
    {
      id: 'sub4',
      name: 'Economics',
      assignedClasses: [
        { classId: '9A', section: 'A' },
      ],
    },
  ],
};

// ─── Students ─────────────────────────────────────────────────────────────────
// Representative students from the teacher's classes (6A, 7A, 8A, 9A).
// In production these come from Supabase; this is the dev/demo fallback.

export const mockStudents: Student[] = [
  // Class 6A
  {
    id: '6A-01',
    name: 'Aarav Sharma',
    attendance: 96,
    grade: 'A+',
    performance: [88, 91, 94, 92, 95, 97],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/aarav/200/200',
  },
  {
    id: '6A-02',
    name: 'Ananya Iyer',
    attendance: 88,
    grade: 'A',
    performance: [82, 85, 88, 84, 87, 90],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/ananya/200/200',
  },
  {
    id: '6A-03',
    name: 'Arjun Mehta',
    attendance: 72,
    grade: 'B',
    performance: [68, 72, 74, 70, 73, 75],
    feesStatus: 'Pending',
    avatar: 'https://picsum.photos/seed/arjun/200/200',
  },
  {
    id: '6A-04',
    name: 'Aisha Khan',
    attendance: 91,
    grade: 'A',
    performance: [85, 88, 86, 89, 90, 92],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/aisha/200/200',
  },
  {
    id: '6A-05',
    name: 'Bhavya Reddy',
    attendance: 64,
    grade: 'C',
    performance: [55, 60, 58, 62, 57, 61],
    feesStatus: 'Overdue',
    avatar: 'https://picsum.photos/seed/bhavya/200/200',
  },
  {
    id: '6A-06',
    name: 'Dev Gupta',
    attendance: 95,
    grade: 'A+',
    performance: [93, 95, 97, 94, 96, 98],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/dev/200/200',
  },
  // Class 7A
  {
    id: '7A-01',
    name: 'Gaurav Tiwari',
    attendance: 89,
    grade: 'B+',
    performance: [78, 80, 83, 81, 82, 85],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/gaurav/200/200',
  },
  {
    id: '7A-02',
    name: 'Isha Pandey',
    attendance: 93,
    grade: 'A',
    performance: [86, 88, 90, 87, 91, 89],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/isha/200/200',
  },
  {
    id: '7A-03',
    name: 'Kabir Malhotra',
    attendance: 78,
    grade: 'B',
    performance: [70, 74, 77, 72, 75, 76],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/kabir/200/200',
  },
  {
    id: '7A-04',
    name: 'Kavya Rao',
    attendance: 66,
    grade: 'C',
    performance: [58, 62, 60, 64, 61, 63],
    feesStatus: 'Overdue',
    avatar: 'https://picsum.photos/seed/kavya/200/200',
  },
  {
    id: '7A-05',
    name: 'Naveen Reddy',
    attendance: 85,
    grade: 'B+',
    performance: [79, 81, 84, 80, 83, 86],
    feesStatus: 'Pending',
    avatar: 'https://picsum.photos/seed/naveen/200/200',
  },
  {
    id: '7A-06',
    name: 'Palak Soni',
    attendance: 98,
    grade: 'A+',
    performance: [94, 96, 98, 95, 97, 99],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/palak/200/200',
  },
  // Class 8A
  {
    id: '8A-01',
    name: 'Tanushree Roy',
    attendance: 90,
    grade: 'A',
    performance: [84, 87, 89, 86, 88, 91],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/tanushree/200/200',
  },
  {
    id: '8A-02',
    name: 'Vedant Jha',
    attendance: 82,
    grade: 'B+',
    performance: [76, 79, 82, 78, 80, 83],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/vedant/200/200',
  },
  {
    id: '8A-03',
    name: 'Vrinda Kapila',
    attendance: 94,
    grade: 'A+',
    performance: [90, 92, 95, 91, 93, 96],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/vrinda/200/200',
  },
  {
    id: '8A-04',
    name: 'Abhinav Khanna',
    attendance: 70,
    grade: 'C+',
    performance: [63, 67, 70, 65, 68, 72],
    feesStatus: 'Pending',
    avatar: 'https://picsum.photos/seed/abhinav/200/200',
  },
  {
    id: '8A-05',
    name: 'Akshita Gulati',
    attendance: 87,
    grade: 'B+',
    performance: [80, 83, 86, 82, 85, 87],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/akshita/200/200',
  },
  {
    id: '8A-06',
    name: 'Zoya Malik',
    attendance: 58,
    grade: 'D',
    performance: [48, 52, 55, 50, 54, 56],
    feesStatus: 'Overdue',
    avatar: 'https://picsum.photos/seed/zoya/200/200',
  },
  // Class 9A
  {
    id: '9A-01',
    name: 'Pragya Goyal',
    attendance: 97,
    grade: 'A+',
    performance: [93, 95, 97, 96, 98, 99],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/pragya/200/200',
  },
  {
    id: '9A-02',
    name: 'Raghav Bansal',
    attendance: 80,
    grade: 'B',
    performance: [74, 77, 80, 76, 79, 81],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/raghav/200/200',
  },
  {
    id: '9A-03',
    name: 'Rashi Kapoor',
    attendance: 92,
    grade: 'A',
    performance: [87, 89, 92, 88, 91, 93],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/rashi/200/200',
  },
  {
    id: '9A-04',
    name: 'Rishi Mehra',
    attendance: 63,
    grade: 'C',
    performance: [56, 60, 63, 58, 61, 64],
    feesStatus: 'Overdue',
    avatar: 'https://picsum.photos/seed/rishi/200/200',
  },
  {
    id: '9A-05',
    name: 'Samridhi Gupta',
    attendance: 86,
    grade: 'B+',
    performance: [80, 82, 85, 81, 84, 87],
    feesStatus: 'Pending',
    avatar: 'https://picsum.photos/seed/samridhi/200/200',
  },
  {
    id: '9A-06',
    name: 'Sanjay Kumar',
    attendance: 75,
    grade: 'B',
    performance: [69, 72, 75, 71, 74, 76],
    feesStatus: 'Paid',
    avatar: 'https://picsum.photos/seed/sanjay/200/200',
  },
];

// ─── Quiz Submissions ─────────────────────────────────────────────────────────
export const mockQuizSubmissions: StudentQuizSubmission[] = [
  {
    id: 'sub-1',
    studentId: '6A-01',
    quizTitle: 'Ancient Civilisations — Unit Test',
    score: 18,
    totalQuestions: 20,
    submittedAt: new Date().toISOString(),
    answers: [{ questionIndex: 0, selectedAnswer: 'Indus Valley', isCorrect: true }],
  },
  {
    id: 'sub-2',
    studentId: '6A-03',
    quizTitle: 'Ancient Civilisations — Unit Test',
    score: 13,
    totalQuestions: 20,
    submittedAt: new Date(Date.now() - 3_600_000).toISOString(),
    answers: [{ questionIndex: 0, selectedAnswer: 'Mesopotamia', isCorrect: false }],
  },
  {
    id: 'sub-3',
    studentId: '6A-06',
    quizTitle: 'Ancient Civilisations — Unit Test',
    score: 20,
    totalQuestions: 20,
    submittedAt: new Date(Date.now() - 7_200_000).toISOString(),
    answers: [],
  },
  {
    id: 'sub-4',
    studentId: '7A-02',
    quizTitle: 'Rivers of India — Geography Quiz',
    score: 8,
    totalQuestions: 10,
    submittedAt: new Date(Date.now() - 14_400_000).toISOString(),
    answers: [],
  },
  {
    id: 'sub-5',
    studentId: '7A-06',
    quizTitle: 'Rivers of India — Geography Quiz',
    score: 10,
    totalQuestions: 10,
    submittedAt: new Date(Date.now() - 500_000).toISOString(),
    answers: [],
  },
  {
    id: 'sub-6',
    studentId: '8A-03',
    quizTitle: 'Indian Constitution — Civics',
    score: 14,
    totalQuestions: 15,
    submittedAt: new Date().toISOString(),
    answers: [],
  },
  {
    id: 'sub-7',
    studentId: '9A-01',
    quizTitle: 'Supply & Demand — Economics',
    score: 19,
    totalQuestions: 20,
    submittedAt: new Date().toISOString(),
    answers: [],
  },
  {
    id: 'sub-8',
    studentId: '9A-04',
    quizTitle: 'Supply & Demand — Economics',
    score: 11,
    totalQuestions: 20,
    submittedAt: new Date(Date.now() - 1_800_000).toISOString(),
    answers: [],
  },
];

// ─── Calendar Events ──────────────────────────────────────────────────────────
export const mockCalendarEvents: CalendarEvent[] = [
  {
    id: 'ev-1',
    title: 'Class 6A — History Unit Test',
    date: new Date().toISOString(),
    type: 'Lecture',
    description: 'Ancient Civilisations — Chapters 1–3',
  },
  {
    id: 'ev-2',
    title: 'Eid-ul-Fitr (Tentative)',
    date: '2026-04-10T00:00:00Z',
    type: 'Holiday',
    isGlobal: true,
  },
  {
    id: 'ev-3',
    title: 'Inter-House Debate Competition',
    date: new Date(Date.now() + 86_400_000 * 5).toISOString(),
    type: 'Activity',
    description: 'Mandatory for all Class 8 students',
  },
  {
    id: 'ev-4',
    title: 'Annual Day Rehearsal',
    date: new Date().toISOString(),
    type: 'Activity',
    isGlobal: true,
  },
  {
    id: 'ev-5',
    title: 'PTM — Parent–Teacher Meeting',
    date: new Date(Date.now() + 86_400_000 * 3).toISOString(),
    type: 'Announcement',
    isGlobal: true,
  },
  {
    id: 'ev-6',
    title: 'Class 9A — Economics Chapter Test',
    date: new Date(Date.now() + 86_400_000 * 7).toISOString(),
    type: 'Lecture',
    description: 'Supply, Demand & Market Structures',
  },
];
